/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;

import ferramentas.CaixaDeDialogo;
import demo.ContaController;
import ferramentas.Formatacao;

/**
 *
 * @author Vinicius
 */
public class InterfaceBanco extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceBanco
     */
   public Conta conta1;
   public Conta conta2;

    public InterfaceBanco() {
        initComponents();
        
        Conexao.abreConexao();
        


    }

    private void atualizarInformacoesTela() {
         ContaController controller = new ContaController();
         float saldoConta1 = controller.buscarSaldo(conta1.getId());
         float saldoConta2 = controller.buscarSaldo(conta2.getId());
         
         conta1.setSaldo(saldoConta1);
         conta2.setSaldo(saldoConta2);
        
        lblConta1.setText(conta1.getNome());
        lblConta2.setText(conta2.getNome());
        lblSaldoConta1.setText(" Saldo:  " + String.valueOf(conta1.getSaldo()));
        lblSaldoConta2.setText(" Saldo:  " + String.valueOf(conta2.getSaldo()));
        lblChequeEspecialConta1.setText(" Cheque Especial: " + String.valueOf(conta1.getCheque_especial()));
        lblChequeEspecialConta2.setText(" Cheque Especial: " + String.valueOf(conta2.getCheque_especial()));
        
        controller.preencher(jtbTabela);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaldoConta1 = new javax.swing.JLabel();
        lblConta2 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        lblConta1 = new javax.swing.JLabel();
        lblSaldoConta2 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        btnTranferirConta1 = new javax.swing.JButton();
        btnTranferirConta2 = new javax.swing.JButton();
        btnSacarConta1 = new javax.swing.JButton();
        btnDepositarConta1 = new javax.swing.JButton();
        lblChequeEspecialConta1 = new javax.swing.JLabel();
        lblChequeEspecialConta2 = new javax.swing.JLabel();
        btnSacarConta2 = new javax.swing.JButton();
        btnDepositarConta2 = new javax.swing.JButton();
        lblData1 = new javax.swing.JLabel();
        txtData1 = new javax.swing.JTextField();
        btnData2 = new javax.swing.JButton();
        btnData1 = new javax.swing.JButton();
        btnData3 = new javax.swing.JButton();
        txtNumeros = new javax.swing.JTextField();
        lblNumeros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblSaldoConta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldoConta1.setText("Saldo 1 ");

        lblConta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConta2.setText("Conta 2");

        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });

        lblConta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConta1.setText("Conta 1");

        lblSaldoConta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldoConta2.setText("Saldo 2");

        txtValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor2ActionPerformed(evt);
            }
        });

        btnTranferirConta1.setText("Transferir");
        btnTranferirConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranferirConta1ActionPerformed(evt);
            }
        });

        btnTranferirConta2.setText("Transferir");
        btnTranferirConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranferirConta2ActionPerformed(evt);
            }
        });

        btnSacarConta1.setText("Sacar");
        btnSacarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConta1ActionPerformed(evt);
            }
        });

        btnDepositarConta1.setText("Depositar");
        btnDepositarConta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarConta1ActionPerformed(evt);
            }
        });

        lblChequeEspecialConta1.setText("Cheque Especial");

        lblChequeEspecialConta2.setText("Cheque Especial");

        btnSacarConta2.setText("Sacar");
        btnSacarConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarConta2ActionPerformed(evt);
            }
        });

        btnDepositarConta2.setText("Depositar");
        btnDepositarConta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarConta2ActionPerformed(evt);
            }
        });

        lblData1.setText("DATA DMY");

        btnData2.setText("CONVERTE PARA AMD");
        btnData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnData2ActionPerformed(evt);
            }
        });

        btnData1.setText("CONVERTE PARA DMA");
        btnData1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnData1ActionPerformed(evt);
            }
        });

        btnData3.setText("APENAS NUMEROS");
        btnData3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnData3ActionPerformed(evt);
            }
        });

        jtbTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtData1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblChequeEspecialConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValor1)
                        .addComponent(btnTranferirConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSacarConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDepositarConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSaldoConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblConta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnData2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnData3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValor2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblChequeEspecialConta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(btnTranferirConta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSacarConta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDepositarConta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblConta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSaldoConta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConta1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSaldoConta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChequeEspecialConta1)
                        .addGap(30, 30, 30)
                        .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTranferirConta1)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacarConta1)
                        .addGap(18, 18, 18)
                        .addComponent(btnDepositarConta1)
                        .addGap(27, 27, 27)
                        .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConta2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoConta2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblChequeEspecialConta2)))
                        .addGap(18, 18, 18)
                        .addComponent(btnTranferirConta2)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacarConta2)
                        .addGap(18, 18, 18)
                        .addComponent(btnDepositarConta2)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnData1)
                            .addComponent(lblData1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnData2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnData3)))
                .addGap(8, 8, 8)
                .addComponent(lblNumeros)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConta1ActionPerformed
        try {
            float valor = Float.parseFloat(txtValor1.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta1, valor);
            if(retorno){
            atualizarInformacoesTela();
            CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
            System.out.println("Operacao de credito" + valor);
        }else{
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operaçao", 'e');
            }
        }catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnSacarConta1ActionPerformed

    private void btnDepositarConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarConta1ActionPerformed

        try {
            float valor = Float.parseFloat(txtValor1.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.debito(conta1, valor);
            if(retorno){
            atualizarInformacoesTela();
            CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
            System.out.println("Operacao de debito" + valor);
        }else{
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operaçao", 'e');
            }
        }catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
    }//GEN-LAST:event_btnDepositarConta1ActionPerformed

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void txtValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor2ActionPerformed

    private void btnTranferirConta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferirConta1ActionPerformed
        try {
            float valor = Float.parseFloat(txtValor1.getText());
           // boolean resultado = conta1.credito(valor);
            ContaController controller = new ContaController();
            boolean resultado = controller.credito(conta1, valor);
            if (resultado) {
               // conta2.debito(valor);
               resultado = controller.debito(conta2,valor);
               if(resultado){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso!", 'i');
               }else{
                   CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operacao!", 'a');
                   
               }
               
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saldo insuficiente!", 'a');
            }

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }

    }//GEN-LAST:event_btnTranferirConta1ActionPerformed

    private void btnTranferirConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferirConta2ActionPerformed
        try {
            float valor = Float.parseFloat(txtValor2.getText());
           // boolean resultado = conta1.credito(valor);
            ContaController controller = new ContaController();
            boolean resultado = controller.credito(conta2, valor);
            if (resultado) {
               // conta2.debito(valor);
               resultado = controller.debito(conta1,valor);
               if(resultado){
                atualizarInformacoesTela();
                CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso!", 'i');
               }else{
                   CaixaDeDialogo.obterinstancia().exibirMensagem("Erro na operacao!", 'a');
                   
               }
               
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Saldo insuficiente!", 'a');
            }

        } catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }

    }//GEN-LAST:event_btnTranferirConta2ActionPerformed

    private void btnSacarConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarConta2ActionPerformed
        try {
            float valor = Float.parseFloat(txtValor2.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.credito(conta2, valor);
            if(retorno){
            atualizarInformacoesTela();
            CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
            System.out.println("Operacao de credito" + valor);
        }else{
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operaçao", 'e');
            }
        }catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }

    }//GEN-LAST:event_btnSacarConta2ActionPerformed

//    private void verificaCamposVazios() {
//
//        if (txtValor1.getText().isEmpty() && txtValor2.getText().isEmpty()) {
//            CaixaDeDialogo.obterinstancia().exibirMensagem("Preencha os campos corretamente!", 'a');
//        }
//    }

    private void btnDepositarConta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarConta2ActionPerformed
        try {
            float valor = Float.parseFloat(txtValor2.getText());
            
            ContaController controller = new ContaController();
            boolean retorno = controller.debito(conta2, valor);
            if(retorno){
            atualizarInformacoesTela();
            CaixaDeDialogo.obterinstancia().exibirMensagem("Operação realizada com sucesso", 'i');
            System.out.println("Operacao de debito" + valor);
        }else{
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro ao realizar operaçao", 'e');
            }
        }catch (Exception ex) {
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }

    }//GEN-LAST:event_btnDepositarConta2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //quando abre a tela
        ContaController controller = new ContaController();
        
         //conta1 = controller.buscar(21);
         conta2 = controller.buscar(22);
          

        atualizarInformacoesTela();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnData1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnData1ActionPerformed
        try{
            
            String retorno = "";
            String data_amd = txtData1.getText();
            retorno = Formatacao.ajustaDataDMA(data_amd);
            
            lblData1.setText(retorno);
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }
                                            
    }//GEN-LAST:event_btnData1ActionPerformed

    private void btnData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnData2ActionPerformed
        try{
            
            String retorno = "";
            String data_dma = txtData1.getText();
            retorno = Formatacao.ajustaDataAMD(data_dma);
            
            lblData1.setText(retorno);
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        }

    }//GEN-LAST:event_btnData2ActionPerformed

    private void btnData3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//GEN-FIRST:event_btnData3ActionPerformed
      
        try{
            
            lblNumeros.setText(Formatacao.removerFormatacao(txtNumeros.getText()));
            
        }catch(Exception ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Erro: " + ex.getMessage(), 'e');
        
                                            
        }
    }//GEN-LAST:event_btnData3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnData1;
    private javax.swing.JButton btnData2;
    private javax.swing.JButton btnData3;
    private javax.swing.JButton btnDepositarConta1;
    private javax.swing.JButton btnDepositarConta2;
    private javax.swing.JButton btnSacarConta1;
    private javax.swing.JButton btnSacarConta2;
    private javax.swing.JButton btnTranferirConta1;
    private javax.swing.JButton btnTranferirConta2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTabela;
    private javax.swing.JLabel lblChequeEspecialConta1;
    private javax.swing.JLabel lblChequeEspecialConta2;
    private javax.swing.JLabel lblConta1;
    private javax.swing.JLabel lblConta2;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel lblSaldoConta1;
    private javax.swing.JLabel lblSaldoConta2;
    private javax.swing.JTextField txtData1;
    private javax.swing.JTextField txtNumeros;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
